services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: financehub
      POSTGRES_USER: financehub
      POSTGRES_PASSWORD: financehub
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U financehub -d financehub"]
      interval: 5s
      timeout: 5s
      retries: 10

  vault:
    image: hashicorp/vault:1.16
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    command: "server -dev"
    cap_add:
      - IPC_LOCK

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/financehub
      SPRING_DATASOURCE_USERNAME: financehub
      SPRING_DATASOURCE_PASSWORD: financehub
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}

    ports:
      - "8080:8080"
